export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_SAVE_SHIPPING_ADDRESS_REQUEST =
  'CART_SAVE_SHIPPING_ADDRESS_REQUEST'
export const CART_SAVE_SHIPPING_ADDRESS_SUCCESS =
  'CART_SAVE_SHIPPING_ADDRESS_SUCCESS'
export const CART_SAVE_SHIPPING_ADDRESS_FAIL = 'CART_SAVE_SHIPPING_ADDRESS_FAIL'
