export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'

export const ORDER_DETIALS_REQUEST = 'ORDER_DETIALS_REQUEST'
export const ORDER_DETIALS_SUCCESS = 'ORDER_DETIALS_SUCCESS'
export const ORDER_DETIALS_FAIL = 'ORDER_DETIALS_FAIL'
