export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGIST_REQUEST = 'USER_REGIST_REQUEST'
export const USER_REGIST_SUCCESS = 'USER_REGIST_SUCCESS'
export const USER_REGIST_FAIL = 'USER_REGIST_FAIL'
