export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PRODUCT_DETIALS_REQUEST = 'PRODUCT_DETIALS_REQUEST'
export const PRODUCT_DETIALS_SUCCESS = 'PRODUCT_DETIALS_SUCCESS'
export const PRODUCT_DETIALS_FAIL = 'PRODUCT_DETIALS_FAIL'
