export const PRODUCT_LIST_SUCCESS = 'PPRODUCT_LIST_REQUEST'
export const PPRODUCT_LIST_REQUEST = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FIAL = 'PRODUCT_LIST_FIAL'

export const PRODUCT_DETAILS_SUCCESS = 'PPRODUCT_DETAILS_REQUEST'
export const PPRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FIAL = 'PRODUCT_DETAILS_FIAL'
